### PR TITLE
LRQA-73668 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRQA-73668

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:stop

**Comment by xbrianlee** [comment]
@brookedalton Just talked to Josh about this change. Could you move [8a734e3](https://github.com/xbrianlee/liferay-portal/pull/724/commits/8a734e395d4563ea1e1a762ca290f9378de622af) to `configure-kibana-x-pack-security-properties`? The new config fits better in that macrodef since we need it when enabling X-Pack Security.

Once you're done with that change go ahead and forward and backport the changes. Thanks!

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by joshchong** [comment]
@brookedalton can you group both echo's in an if statement like:
```
<if>
    <equals arg1="${elasticsearch.jdk11.enabled}" arg2="true" />
````
and remove the `if:true="${elasticsearch.jdk11.enabled}"` statements?

**Comment by joshchong** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Pull request closed without merging**
