### PR TITLE
LPS-142910 Move comments into top header bar

### PR DESCRIPTION
**Pull request by stsquared99**
Hey @xbrianlee could you check on the tests for this? Thanks!

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
Hi @stsquared99, the results look good and only one test need to update and I sent the pr to you on https://github.com/stsquared99/liferay-portal/pull/182.

**Comment by stsquared99** [comment]
@xbrianlee @suilin Thank you both!

**Pull request closed without merging**
