### PR TITLE
LPS-144422 Add edit in production/publication actions

### PR DESCRIPTION
**Pull request by stsquared99**
@xbrianlee Sorry, can I get this retested? I found an additional behavior fix needed. I can discuss during our standup. Thanks!

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by stsquared99** [comment]
@xbrianlee In the meantime, maybe this can be a starting point just for this pull?

1. Overall, when appropriate, discard and edit in publication and production urls will show when reviewing publications changes, regardless of what publication is active. In the past, edit url would only show when publication was active. Now you are simply give a confirm dialog when a switch in publication is required. Discard does not require the publication to be active so show it always.
2. Edit in production shows and functions properly when production/publication is active for modified entries (like a journal folder)
3. Edit in production shows and functions properly when production/publication is active for new versioned entries (like a journal article)
4. Edit in production shows and functions properly when production/publication is active in conflicts page for a modification conflict (like a duplicate journal folder name)

Consideration:
- Journal Folder's edit url includes a permission check. So potentially, if you create a journal folder in a publication and review it while in production, you will not generate an edit url. I made sure to account for this
1. Create journal folder in production
2. Review journal folder in review changes, verify edit action in dropdown
3. Switch to production
4. Verify edit action

**Comment by xbrianlee** [comment]
@stsquared99 Thanks this is perfect! I'll discuss what other info would be helpful with Linda later today and start a discussion on Slack with you guys hopefully tomorrow.

I'm going to wait until the fix for [LPS-147045](https://issues.liferay.com/browse/LPS-147045) makes it upstream to test this again (should be in the next few hours). This was a major Web Content regression that caused failures for us and affects what we see in Publications conflict view.

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
@stsquared99 The PR results here look good. Could you fix the rebase conflict and then forward to liferay-core-infra?

Also I did have a question about when the edit in production and publication actions show up. I noticed when creating a modification conflict for WC Folder, Documents, and other assets, these actions show up, but when creating a modification conflict for  Dynamic Data Mapping Structure, my only action was to discard the change. Is there something specific about this asset type that doesn't allow edit actions?

**Comment by stsquared99** [comment]
@xbrianlee for DDM Structure, the edit url is simply not implemented in the display renderer, we may have just missed it. If you think that should be added, I guess that could be reported as a bug?

**Comment by stsquared99** [comment]
Resent: https://github.com/liferay-core-infra/liferay-portal/pull/332

**Pull request closed without merging**
