### PR TITLE
LRQA-74218 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRQA-74218

### CODE REVIEW

**Comment by joshchong** [comment]
hey @brookedalton were we able to test whether removing the steps for ```WaitForConsoleTextPresent(value1 = "Returning connection with ID: __REMOTE__");``` produces stable results with your change?

**Comment by brookedalton** [comment]
Hi @joshchong, when I tried it locally the test failed - I guess the node panel was present in the UI and the "stopping elasticsearch" was present in the console log but search still wasn't ready so when the test moved to view the search portlet in the home page it was unavailable and the test failed

**Comment by joshchong** [comment]
Hm that's really odd. I thought the node panel only shows up after the `__REMOTE__` server logs. I guess we can look into this later. @xbrianlee I'm okay with these changes for now if you are.

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
