### PR TITLE
LRQA-58528 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LRQA-58528
CC: @dellawang

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by yichenroy** [comment]
ci:test:security:nocompile

Restarting test, previous test encountered network issue and is unable to respond.

**Comment by xbrianlee** [comment]
ci:stop

@dellawang Can you group the assertions into macros that way the testcase looks less cluttered? If the test passes locally, you can forward to BChan.

**Comment by dellawang** [comment]
> ci:stop
> 
> @dellawang Can you group the assertions into macros that way the testcase looks less cluttered? If the test passes locally, you can forward to BChan.

@xbrianlee OK, I got it. Thank you.

**Pull request closed without merging**
