### PR TITLE
LPS-146796 User unable to login after resetting password if last in Publication

### PR DESCRIPTION
**Pull request by stsquared99**
@xbrianlee This is a weird one. Maybe testing flow is the best place to start.
1. Add a user Joe Bloggs
2. Enable Publications
3. Add a publication TestPub
4. Invite Joe Bloggs as an Editor to Test Pub
5. Impersonate Joe Bloggs
6. (Impersonating) Set TestPub as active publication
7. (Joe Bloggs) Login as Joe Bloggs and go through the Terms, Password, and Reminder, all while TestPub is active. You can verify that it is the active publication once those steps are complete.

Current behavior is to just get stuck on these steps, the submit actions don't do anything. For password it just throws a not CT supported exception.

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
Hey @xbrianlee, have you had a chance to take a look at this? This is probably the higher priority of my pulls, I know I've thrown a bunch at you lately. Thanks!

**Comment by xbrianlee** [comment]
@stsquared99 Sorry Sam, I missed this one. I'll take a look at it first thing tomorrow.

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@stsquared99 Test results look good. I also manually tested the user flow addressed by this bug ticket. Created a functional test ticket to cover this scenario - LPS-147570.

**Comment by stsquared99** [comment]
Thanks @xbrianlee. Can you think of any other scenarios or considerations we might need to cover?

**Comment by stsquared99** [comment]
Hey @xbrianlee, no worries. I'm more being careful in terms of whether my change can cause any other problems or unintended effects. Should be fine since it only affects a couple methods and in publication mode only. If you feel good with it then I can't think of anything else. Did you have any additional commits to add at this point? Otherwise I can rebase and forward it myself. Thanks!

**Comment by xbrianlee** [comment]
@stsquared99 Nothing for this ticket. We'll add this test later since it is an edge case. Thanks!

**Comment by stsquared99** [comment]
ci:close

**Comment by stsquared99** [comment]
Forwarded: https://github.com/liferay-core-infra/liferay-portal/pull/350

**Pull request closed without merging**
