### PR TITLE
LPS-147674 After upgrading from 7.3 to 7.4, the Publications User role doesn't have all of it's permissions


### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-147674

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
@xbrianlee I think your functional test should be good enough. Once you're comfortable with this pull can you go ahead and forward it? Thanks!

**Comment by xbrianlee** [comment]
ci:test:publications

Re-running the publications test suite since the upgrade test failed for unrelated reasons. All other test results look good.

**Pull request closed without merging**
