### PR TITLE
master-qa-48197-1

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-48218

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:security:norebase

**Comment by suilin** [comment]
ci:test:sf:norebase

**Comment by suilin** [comment]
@ xbrianlee, this pr fail to rebase on master since there is conflict file: modules/apps/portal-settings/portal-settings-authentication-ldap-web/bnd.bnd.

**Comment by xbrianlee** [comment]
ci:test:security:norebase

**Pull request closed without merging**
