### PR TITLE
LPS-183473 While in a Publication, entities deleted in Recycle Bin are deleted permanently

### PR DESCRIPTION
**Pull request by xbrianlee**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@david-truong We have 2 functional tests failing due to a bug. Can you take a look
1. Create WC Folder
2. Enable Publications
3. Create Publication - P1
4. Add WC in the WC Folder
5. Rename WC Folder
6. Create Publication - P2
7. Delete WC Folder
8. Empty Recycle Bin
9. Publish P2
10. Select P1
11. Revisit Web Content Admin

Expected Result: Edited Web Content Folder shows up.
Actual Result: Nothing shows up under Web Content Admin and the following error gets thrown.
```
2023-06-16 18:33:57.303 ERROR [http-nio-8080-exec-5][IncludeTag:128] Current URL /group/site-name/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet generates exception: java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=20096, name=com.liferay.journal.model.JournalFolder, primKey=33794, scope=4}
com.liferay.portal.kernel.exception.NoSuchResourcePermissionException: {companyId=20096, name=com.liferay.journal.model.JournalFolder, primKey=33794, scope=4}
```

**Comment by david-truong** [comment]
@xbrianlee are you sure this is a regression?  seems like it would have always worked this way.

**Comment by xbrianlee** [comment]
ci:test:publications

Retesting this. I wasn't able to reproduce the test failure locally.

**Comment by suilin** [comment]
Hi @david-truong, I can reproduce the issue that Brian mentioned above, the reason why it fails to publish P1 since there is still a conflict change under Web Content Folder. Actually there are two conflict changes when publishing P1,
1. `Test Test modified a Asset 1 Minute ago. WC Folder Edited`
2. `Test Test modified a Web Content Folder 1 Minute ago. WC Folder Edited`
When we discard the `Asset` one, the `Web Content Folder` conflict one will still present, so we fail to publish P1, if we discard the` Web Content Folder` conflict one the issue won't happen. I remember we can discard all of them before, could you look at it?

Another regression bug: 
1. Enable Publication
2. Add a new web content
3. Add a new publication "P1"
4. Delete the web content
5. Add a new publication "P2"
6. Edit the new web content
7. Work on Publication "P1"
8. Publish "P1"
9. Navigate to Web content, assert there is no web content
10. Work on Publication "P2"
11. Navigate to Web Content

Result: The edited web content is gone, the edited web content should show up.

cc @xbrianlee

**Comment by david-truong** [comment]
Yes that is going to result in a conflict but I think that was always the case.  I tried the same thing in u69 and it resulted in the same thing.  What happened after the recycle bin was disabled? Did we restore the folder?

**Comment by xbrianlee** [comment]
There was always a conflict so the folder was never restored. But when we discard the `Asset` or `Web Content Folder` change (in Linda's screenshot), the other would always get discarded too which would allow the remainder for the publication to publish.

**Comment by david-truong** [comment]
Ahh okay so discard the other ones and then publish?

**Comment by xbrianlee** [comment]
Yeah, discard the `Asset` or `Web Content Folder` change and then publish

**Pull request closed without merging**
