### PR TITLE
LPS-131354, LRQA-67471 | master

### PR DESCRIPTION
**Pull request by brookedalton**

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search-blueprints:norebase

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:test:search-blueprints:norebase

**Comment by brookedalton** [comment]
ci:test:search-blueprints:norebase

**Comment by xbrianlee** [comment]
Continued in https://github.com/xbrianlee/liferay-portal/pull/606

**Pull request closed without merging**
