### PR TITLE
master-qa-60044

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LRQA-60044

Added a new test case to verify a specific error message in a virtual instance in saas

CC @xbrianlee

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by xbrianlee** [comment]
Nice job on this PR @gaborlovasdotcom! One minor change: Can you rename the commit message? It should be more descriptive so that we can identify the change without having to click into the commit. For example, "Add testcase to assert error messages for instance-scoped actions users can't make".

**Comment by gaborlovasdotcom** [comment]
Continued in: https://github.com/gaborlovasdotcom/liferay-portal/pull/40

**Pull request closed without merging**
