### PR TITLE
master-qa-65698

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LRQA-65698

from: https://github.com/gaborlovasdotcom/liferay-portal/pull/61

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by xbrianlee** [comment]
@gaborlovasdotcom Is there any other assertion we can add to this test? The assertions seem to be the same as OAuth2#AuthorizeExternalApplication

**Comment by gaborlovasdotcom** [comment]
> @gaborlovasdotcom Is there any other assertion we can add to this test? The assertions seem to be the same as OAuth2#AuthorizeExternalApplication

Not really, at this scenario we leave our the manual authorization steps, which is exist at: https://github.com/xbrianlee/liferay-portal/blob/e8a9caf336f9ae07d327f664dd9617e06ddd7709/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/security/oauth2/OAuth2.testcase#L505

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
