### PR TITLE
LPS-166987 LPS-167286 portal-search-solr8-impl: Update test

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-167286

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by suilin** [comment]
Hi @xbrianlee, there are four issues found in this PR:

- The same as the previous PR: There is no Explain displayed when searching with Search Insights:
1. Add a new page "Solr Page"
2. Add a new web content "apple"
3. Navigate to Search page and add Search Insights widget
4. Check Enable Score Explanation
5. Search "apple" in search embedded portlet
6. There is no explain text displayed, and JSONException throws, [here is console log](https://gist.github.com/suilin/80280723b35df059bc45873b46602882)

- Search with Quotes doesn't work with solr, all of the asssets will display.
1. Add a new Blogs Entry with tag `tag name`
2. Search with "tag name1"
3. The blog displays

- Finished indexing dictionary spellchecker/dictionary_de_DE.txt" is not present in console after enabled index.search.spell.checker.

- Test-fix issue, we should update SolrSearch#SearchContentPagesSmoke, add the Search Results with `collectionName = "Search"`.

**Comment by xbrianlee** [comment]
ci:test:search-solr

Trying what Tibor suggested [here](https://issues.liferay.com/browse/LPS-168594?focusedCommentId=2802749&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2802749)

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Pull request closed without merging**
