### PR TITLE
LPS-190389

### PR DESCRIPTION
**Pull request by xbrianlee**
Original PR: https://github.com/liferay-publications/liferay-portal/pull/699

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
