### PR TITLE
master-qa-47418

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-47418

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:security

**Comment by suilin** [comment]
@GinsonRen @brianwulbern

**Comment by xbrianlee** [comment]
@suilin Does this testcase work without restarting the server? Could you test it manually?
_Supposedly_ you just need to connect the LDAP server. Sorry if there were any bad examples in the LDAP testcase...need to go back eventually and redo any tests that unnecessarily restart.

**Comment by suilin** [comment]
@xbrianlee I have verified it on local, the LDAP users can be imported without restarting the server but it needs to wait a moment since the important Interval is 10 s, I can use pause function or shorten the Import Interval instead of restarting the server? Is this way available?

**Comment by xbrianlee** [comment]
@suilin Can you try changing "Import Interval" in Instance Settings? That should work.

**Comment by suilin** [comment]
@xbrianlee Verify the result as following:
1. Shorten the Import Interval still doesn't work.
2. Can be work with this way: On idp I remove the steps restart and assert the LDAP user displays on Users and Organizations, instead, log in with LDAP user on idp to make sure the LDAP user has been imported(it's necessary, if not when sign in with LDAP user on sp it will direct to idp url and doesn't import the ldap user on sp). Is it available?

**Comment by xbrianlee** [comment]
@suilin Let's just keep it simple and use the pause function in that case. Is there a bug with Import Interval or is POSHI just too fast?

**Comment by suilin** [comment]
@xbrianlee * Sorry, I should comment more detailed about my verification.
	* It should be a bug with Import Interval, the LDAP user imported doesn't depend on Import Interval and it's not stable, when I change Import Interval to 1, it still need few minutes.

* And the following methods can assert the LDAP user imported successfully: 
	* Method 1: Add pause function:
Since it's random on imported, it's hard to determine the pause time. So it's necessary to add a while loop to assert the user imported on pause.
	* Method 2: Login the LDAP user first:
After the LDAP user log in, the user is imported and can be displayed on Users and Organizations immediately (About this case more details on latest comment 2)
	* Method 3: Restart the bundle
After restarting the sever the LDAP user can be imported.

* And I found all of the LDAP tests are using Method 3: Restart the bundle, I'm not sure which is best method, need we update them, or creating a bug ticket to track, thanks.

**Comment by xbrianlee** [comment]
@suilin Sorry for the delay. We can stick with Method 3 if it's the most consistent. Thanks so much for looking into this. Can you file a bug ticket for _Import Interval_ please?

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/70644

**Comment by suilin** [comment]
@xbrianlee For the Import Interval issue it doesn't a bug more [detail](https://issues.liferay.com/browse/LPS-76968?focusedCommentId=1228284&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1228284) sorry, I should find it before. Since the commits was sent before LPS-90255, so it will fail to go to instance setting, I will create  LRQA ticket to fix it.

**Pull request closed without merging**
