### PR TITLE
LPS-111013 | master

### PR DESCRIPTION
**Pull request by xbrianlee**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
ci:stop

**Comment by xbrianlee** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
see https://github.com/xbrianlee/liferay-portal-ee/pull/274

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
