### PR TITLE
master-qa-66063

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LRQA-66063

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test.sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
