### PR TITLE
master-qa-52698

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-52698

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:search

**Comment by suilin** [comment]
ci:test:search-es7

**Comment by suilin** [comment]
ci:test

**Comment by suilin** [comment]
@xbrianlee, I have checked ci:test:search, citest:search-es7 and ci:test, all of them can print indices.

**Comment by suilin** [comment]
@xbrianlee, I have checked ci:test:search, citest:search-es7 and ci:test, all of them can print indices.

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/81069

**Pull request closed without merging**
