### PR TITLE
master-qa-47359

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-47359

This is only for master, thanks.

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:security

**Comment by xbrianlee** [comment]
Sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69306

**Comment by suilin** [comment]
cc @GinsonRen @brianwulbern

**Pull request closed without merging**
