### PR TITLE
master-qa-65267-2

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LRQA-65267

Simple version, using existing macros

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by xbrianlee** [comment]
Continued in https://github.com/xbrianlee/liferay-portal/pull/576

**Pull request closed without merging**
