### PR TITLE
LRQA-63702 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRQA-63702

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward

LGTM!

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
