### PR TITLE
LRQA-48197 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-48197

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:security

**Comment by xbrianlee** [comment]
ci:test:security:norebase

**Comment by suilin** [comment]
ci:test:security:norebase

**Comment by xbrianlee** [comment]
Sent to https://github.com/xbrianlee/liferay-portal/pull/283

**Pull request closed without merging**
