### PR TITLE
LRQA-57475 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-57475

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:search:nocompile

**Comment by xbrianlee** [comment]
ci:test:search:nocompile

**Comment by xbrianlee** [comment]
ci:test:search:nocompile

**Comment by xbrianlee** [comment]
ci:test:search:nocompile

**Comment by suilin** [comment]
ci:test:search-solr:nocompile

**Comment by suilin** [comment]
ci:test:search-solr:nocompile

**Comment by xbrianlee** [comment]
See https://github.com/suilin/liferay-portal/pull/281

**Pull request closed without merging**
