### PR TITLE
[master] Publications Canary

### PR DESCRIPTION
**Pull request by xbrianlee**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
new PR: https://github.com/xbrianlee/liferay-portal/pull/659

**Comment by suilin** [comment]
ci:close

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments:nocompile

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Pull request closed without merging**
