### PR TITLE
LPS-76322 Clear permanent tracked styles when language changes

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @xbrianlee, I'm sending this one to you just to make sure this actually fixes the issue described by LPS-76322. Let me know if you have any questions.

Thx

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @brunobasto, I've sent you back this with a different approach to avoid evaluating the wrong styles and before flipping and also keep the screen state in better shape. See https://github.com/brunobasto/liferay-portal/pull/893

**Comment by brunobasto** [comment]
Cool. Will resend.

**Comment by xbrianlee** [comment]
@brunobasto Sorry, I was out last week. Could you please send your updated PR to Albert? Thanks 😄

**Comment by brunobasto** [comment]
Hey @xbrianlee, I already sent it to Chema and it got merged.

Thanks

**Pull request closed without merging**
