### PR TITLE
LPS-146644 Publications User role should be given permission to create publications

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-146644

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
@stsquared99 Is there an upgrade path for 7.3? I was able to upgrade from master upstream to this branch successfully and the Publications User role has the correct permissions, however when upgrading from 7.3, the Publications User role doesn't (see [this screenshot](https://testray.liferay.com/reports/production/logs/2022-02/test-1-35/test-portal-acceptance-pullrequest(master)/675/functional-upgrade-tomcat90-mysql57-jdk8/0/0/LocalFile.PublicationsUpgrade_ViewPublicationsUserRolePermissionsArchive7310/screenshots/before2.jpg.gz)).

Here's the 7.3.10 database dump that we used for testing: https://issues.liferay.com/secure/attachment/440823/data-archive-publications-mysql.zip.

**Comment by stsquared99** [comment]
@xbrianlee Sorry for the delay on the follow up. There actually isn't an upgrade path for 7.3, because the publications user role was only added in the Invite users feature https://issues.liferay.com/browse/LPS-129709 which we did not backport

**Comment by xbrianlee** [comment]
@stsquared99 No problem! So just to be clear, if users upgrade from 7.3, they have to manually add in the correct permissions for the Publications User. Is this the expected behavior?

**Comment by stsquared99** [comment]
@xbrianlee Sorry, what I meant is the Publications User role doesn't exist at all in 7.3, it's a feature added only in 7.4. Thanks

**Pull request closed without merging**
