### PR TITLE
master-qa-52699

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-52699

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:search:nocompile

**Comment by suilin** [comment]
ci:test:search-es7:nocompile

**Comment by suilin** [comment]
ci:test:search-solr:nocompile

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/81950

**Pull request closed without merging**
