### PR TITLE
LPS-163295 - Workflow tasks not created in virtual instances when the database is partitioned

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee could you add your functional tests to this pr

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
@david-truong Could you push a fix for the compile error above?
```
 [parallel] /opt/dev/projects/github/liferay-portal/portal-kernel/src/com/liferay/portal/kernel/security/auth/CompanyThreadLocal.java:104: error: incompatible types: int cannot be converted to Long
 [parallel]       companyId, CTCollectionThreadLocal.CT_COLLECTION_ID_PRODUCTION);
 ```
 
Also I won't be able to add the functional test until the Upgrade team fixes [LPS-164991 (https://issues.liferay.com/browse/LPS-164991). I'm hesitant to merge the test without getting a clean run on CI since it's more environment-focused.

**Comment by david-truong** [comment]
@xbrianlee fixed can you try again?

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:workflow

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/124565

**Pull request closed without merging**
