### PR TITLE
LRQA-40256, LRQA-40861, LRQA-40847 | master

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LRQA-40256
https://issues.liferay.com/browse/LRQA-40861
https://issues.liferay.com/browse/LRQA-40847

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:es6

**Comment by joshchong** [comment]
ci:test:es6

**Comment by joshchong** [comment]
ci:test:es6

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/58702

**Pull request closed without merging**
