### PR TITLE
master-qa-47377

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-47377

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:security

**Comment by suilin** [comment]
cc @GinsonRen @brianwulbern

**Comment by joshchong** [comment]
ci:close

**Comment by joshchong** [comment]
[Closing per comment here](https://issues.liferay.com/browse/LRQA-47377?focusedCommentId=1732562&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1732562)

**Pull request closed without merging**
