### PR TITLE
LPS-67830

### PR DESCRIPTION
**Pull request by ksuetani**
https://issues.liferay.com/browse/LRQA-30248
https://issues.liferay.com/browse/LRQA-30920

The changes for LRQA-30248 are for master only. Another PR will be sent to fix ee-7.0.x failures.

### CODE REVIEW

**Comment by brianwulbern** [comment]
@xbrianlee please backport to ee-7.0.x and/or cc me in your pull to BChan.  Thanks!

**Comment by brianwulbern** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Review for this PR is pending an update

**Comment by ksuetani** [comment]
ci:retest

**Comment by ksuetani** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Pushed to ALee.
https://github.com/alee8888/liferay-portal/pull/446

**Pull request closed without merging**
