### PR TITLE
Master qa 52715

### PR DESCRIPTION
**Pull request by dellawang**
https://issues.liferay.com/browse/LRQA-52715

### CODE REVIEW

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:oauth2

**Comment by dellawang** [comment]
ci:test:oauth2

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/79647

**Pull request closed without merging**
