### PR TITLE
LPS-146644 Publications User role should be given permission to create publications

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
Hey @xbrianlee can you help me test this? It involves and upgrade so I wanna make sure I get it right. Thanks!

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by xbrianlee** [comment]
ci:test:publications-environments:norebase

**Comment by xbrianlee** [comment]
ci:test:relevant:norebase

**Comment by stsquared99** [comment]
@xbrianlee What's the usual testing approach/mentality for an upgrade like this? Is manual testing enough to make sure that it works properly in terms of assigning/verifying permissions? Thanks

**Comment by xbrianlee** [comment]
@stsquared99 For upgrades, we run our test suites to make sure we don't have any obvious failures - usually we find upgrade errors or environment-specific failures here. Then manual testing will help us determine if the specific upgrade process yields the correct change.

To help with manual testing, could you clarify what should happen when upgrading the old Publications User role?

**Comment by stsquared99** [comment]
@xbrianlee Manuel testing for the upgrade needs to verify that currently a Publications User will have no create publication permission, and after the upgrade does. Manual testing the overall change is just to see if the new code, when enabling Publications for the first time, gives the create permission properly.
Hopefully it's pretty straight forward, I just wanted to make sure someone besides myself actually tests it.

Is there a better way in the future to make note of concerns like this that better fit your processes? I would definitely want to learn and adapt to that. Thanks!

**Comment by xbrianlee** [comment]
@stsquared99 This is what I'm seeing:
1. Publication Users are able to publish Publications they are an owner of
2. Publications Users can't publish Publications they are not owners of even if they have Publisher or Inviter roles for a Publication
3. Publications Users can invite other users if they have the Inviter role for a Publication

Is this all expected?

**Comment by stsquared99** [comment]
@xbrianlee Sorry, this is getting mixed up with the Inviter role permission fix. This is to adjust the permissions for the Publications User role that is auto generated in Roles Admin when you enable publications on a company. Currently that role just lets you access the Publications portlet with no additional permissions. It is auto assigned when you invite a user to a specific publication. We want to allow that role to have create publication permissions as well. Does that make more sense?
Thanks!

**Comment by xbrianlee** [comment]
@stsquared99 Ah I get it now! You're right I'm getting the two tickets mixed.

**Comment by xbrianlee** [comment]
Running new functional test in https://github.com/xbrianlee/liferay-portal/pull/701

**Pull request closed without merging**
