### PR TITLE
LPS-118138 Deprecate because it's not longer useful

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
hey @xbrianlee, do you think the errors can be related with the changes?

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/92105

**Pull request closed without merging**
