### PR TITLE
LPS-182821 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-182821

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/134109

**Pull request closed without merging**
