### PR TITLE
LPS-140981 Use history with pagination and filtering parameters

### PR DESCRIPTION
**Pull request by stsquared99**
@xbrianlee Can you take a look? Hopefully the ticket gives you enough info about the changes here. Should only affect browser history behavior and some pagination updates when you reduce the total number of pages via a filtering change.

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
@stsquared99 These test results look good. There are no new test failures. I also did a quick smoke test on the test bundle and the story seems to be implemented correctly. Is this ok to forward to BChan or will someone else need to review this first?

**Comment by stsquared99** [comment]
@xbrianlee Go ahead and forward it, thanks!

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
