### PR TITLE
LPS-185003 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-185003

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:forward

**Comment by joshchong** [comment]
hey @brookedalton @xbrianlee, I closed the PR to bchan bc I'm wondering if we can do this a different way.

@brookedalton can you check if it's possible to exclude tests with a wildcard? running the local job summary command should be enough to let us know. something like:
```
(test.class.method.name !~ SearchUpgrade#*ResultRankings*) AND \
(test.class.method.name !~ SearchUpgrade#*SXP*) AND \
(test.class.method.name !~ SearchUpgrade#*Synonyms*) AND \
```
If so that would be more clear and future proof.

**Comment by brookedalton** [comment]
Hey Josh, I tried         
```
        (test.class.method.name !~ SearchUpgrade#*ResultRankings*) AND \
        (test.class.method.name !~ SearchUpgrade#*SXP*) AND \
        (test.class.method.name !~ SearchUpgrade#*Synonyms*) AND \
``` 
and 
```
        (test.class.method.name !~ SearchUpgrade#ViewResultRankings*) AND \
        (test.class.method.name !~ SearchUpgrade#ViewSXP*) AND \
        (test.class.method.name !~ SearchUpgrade#ViewSynonyms*) AND \
```
but they were still caught by the PQL 😕

**Comment by xbrianlee** [comment]
What do you guys think about setting `property testray.component.names = "Search Experiences";` for those upgrade tests?

**Comment by joshchong** [comment]
@brookedalton ah ok, I'll reopen the pr to bchan then.

@xbrianlee I feel like making changes in the poshi tests makes things less clear, like someone looking at the test wouldn't know why it's there or we might use that property for something else in the future. I'd prefer if we exclude things explicitly in the suite itself.

**Comment by xbrianlee** [comment]
Yeah I agree that it's more visible how we have it now. I thought you were worried about how verbose it was getting 😄

**Comment by joshchong** [comment]
fyi I pushed up some changes here: https://github.com/brianchandotcom/liferay-portal/pull/139833/commits/0642c767e906738fa3b56bf2af1fa3d46b521fab

I realized we don't need wildcards since we are using a contains operator

**Pull request closed without merging**
