### PR TITLE
master | 30686-3

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LRQA-30686

Added fix for elastic search stop for unix.

### CODE REVIEW

**Comment by joshchong** [comment]
ci:reopen

**Comment by joshchong** [comment]
ci:retest

**Comment by xbrianlee** [comment]
@joshchong Really nice job on this!

Sent to:
https://github.com/brianchandotcom/liferay-portal/pull/53293
https://github.com/GinsonRen/liferay-portal-ee/pull/492

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Pull request closed without merging**
