### PR TITLE
[master] Publications Canary

### PR DESCRIPTION
**Pull request by suilin**

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications:nocompile

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Pull request closed without merging**
