### PR TITLE
Lps 102798

### PR DESCRIPTION
**Pull request by shuyangzhou**
This should have covered LPS-106300, but not sure whether it will affect others, please run through necessary CI coverage and scan the results.

CC @arboliveira

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-es7

**Comment by xbrianlee** [comment]
ci:test

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-es7

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:search-es7

**Comment by shuyangzhou** [comment]
@epgarcia can you check whether this pull fixes https://issues.liferay.com/browse/LPS-106351 ? I follow the recorded instructions, this pull should have the same behavior as in the video.

But the issue @xbrianlee mentioned here https://issues.liferay.com/browse/LPS-106351?focusedCommentId=2046743&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2046743 is still there. And this issue also shows with @pavel-savinov 's original fix, to me this is something not related to LPS-102798. It is a separate issue that needs to be handled.

And @xbrianlee please check against all the search related issues. I tested locally, they seem to be all working now.

If all issues are fixed by this pull, we can go with this for now. But @pavel-savinov , see https://github.com/xbrianlee/liferay-portal/pull/394/commits/d1d55e8c6e8ae69ecc7616b387e76bc885e95111 , we will need to use a better way to indentify fragment portlet instance, rather than using the hardcoded "0" check. We can do this later.

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Thanks @shuyangzhou, I'm reviewing it and then I'll forward it to @arboliveira for his final confirmation.

**Comment by shuyangzhou** [comment]
@xbrianlee has verified all the related tickets. Sent to Brian at https://github.com/brianchandotcom/liferay-portal/pull/82620

**Pull request closed without merging**
