### PR TITLE
LRQA-57134 Add a new test to check refresh token's lifetime variable …

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
…operates as expected

LRQA-57134 Add a new test to check refresh token's lifetime variable operates as expected

----
Updated with the changes requested in PR: https://github.com/xbrianlee/liferay-portal/pull/445

CC: @xbrianlee , @manoelcyreno

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Continued in https://github.com/xbrianlee/liferay-portal/pull/448

**Pull request closed without merging**
