### PR TITLE
LPS-147674 After upgrading from 7.3 to 7.4, the Publications User role doesn't have all of it's permissions

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test

**Comment by xbrianlee** [comment]
@stsquared99 Would it make sense to combine the changes in this PR with https://github.com/xbrianlee/liferay-portal/pull/701? The upgrade functional test I added there actually covers this bug.

**Comment by stsquared99** [comment]
@xbrianlee Can we handle these separately, since this is a full on bug fix? So maybe add the upgrade functional test to this one, and when this is merged we can just adjust the permissions for the other ticket. I'm going to see about writing an upgrade test on my part as well for this.

**Comment by xbrianlee** [comment]
@stsquared99 Ok! I'll add the functional test to this PR and send an update to that test when LPS-146644 is merged.

**Comment by xbrianlee** [comment]
Continued in https://github.com/xbrianlee/liferay-portal/pull/707

**Pull request closed without merging**
