### PR TITLE
LRQA-52992 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-52992

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-es7

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-es7

**Comment by xbrianlee** [comment]
ci:stop

**Comment by xbrianlee** [comment]
ci:stop

**Comment by xbrianlee** [comment]
ci:test:search:norebase

**Comment by xbrianlee** [comment]
ci:test:search-es7:norebase

**Comment by xbrianlee** [comment]
ci:stop

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-es7

**Comment by suilin** [comment]
ci:test:search-es7

**Comment by suilin** [comment]
ci:test:search

**Pull request closed without merging**
