### PR TITLE
LRQA-71795, LRQA-71793 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRQA-71795
https://issues.liferay.com/browse/LRQA-71793

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/110345

**Pull request closed without merging**
