### PR TITLE
LPS-177150

### PR DESCRIPTION
**Pull request by CaiocSiqueira**
https://issues.liferay.com/browse/LPS-177150

Original pull request: https://github.com/CaiocSiqueira/liferay-portal/pull/29

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/133358

**Pull request closed without merging**
