### PR TITLE
master-qa-48437

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-48437

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:security

**Comment by xbrianlee** [comment]
ci:test:saml:478cafc69595d43ccda9e18dd9bc8d2eef1574e0

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/72362.

Asked Product Team for clarification on the keep-alive bug.

**Pull request closed without merging**
